version: "3.2"
services:
  app:
    command: node src/server.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      APIKEY: ${APIKEY}
  # database:
  #   image: 'mongo'
  #   container_name: 'node-task-db'
  #   environment:
  #     - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USR}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}
  #   volumes:
  #     - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  #     - ./mongo-volume:/data/db
  #   ports:
  #     - '27017-27019:27017-27019'